name: ci

on:
  push:
  pull_request:
  schedule:
    - cron: '0 23 * * 5' # Every Friday at 23:00

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

# Build and test in Ubuntu VM provided by Github CI
    - uses: actions/checkout@v3
    - run: |
        set -ex
        sudo apt-get -qq update > /dev/null < /dev/null
        sudo apt-get -qq install libsystemd-dev > /dev/null < /dev/null
    - run: make
    - run: make test
    - run: git clean -dxff

# Build in Debian container with libsystemd
# ("make test" does not work in container)
    - name: Build in Debian container with libsystemd
      uses: addnab/docker-run-action@v3
      with:
        image: debian:bullseye
        options: -v ${{ github.workspace }}:/work
        run: |
          set -ex
          apt-get -qq update > /dev/null < /dev/null
          apt-get -qq install make gcc libsystemd-dev > /dev/null < /dev/null
          cd /work
          make
    - run: git clean -dxff

# Build in Debian container with libelogind
# ("make test" does not work in container)
    - name: Build in Debian container with libelogind
      uses: addnab/docker-run-action@v3
      with:
        image: debian:bullseye
        options: -v ${{ github.workspace }}:/work
        run: |
          set -ex
          apt-get -qq update > /dev/null < /dev/null
          apt-get -qq install make gcc pkg-config libelogind-dev > /dev/null < /dev/null
          cd /work
          make
    - run: git clean -dxff

# Build in Fedora container with libsystemd
# ("make test" does not work in container)
    - name: Build in Fedora container
      uses: addnab/docker-run-action@v3
      with:
        image: fedora:36
        options: -v ${{ github.workspace }}:/work
        run: |
          set -ex
          dnf -qy install make gcc systemd-devel
          cd /work
          make
    - run: git clean -dxff
